modLoader="javafml"
license="LGPLv3"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/GregTech-Intergalactical/GregTech/issues"

[[mods]]
modId="gti"
version="${version}"
displayName="GTI"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/GregTech-Intergalactical/GregTech"
#logoFile="gregtech.png"
credits="GregoriusTechneticies for his previous versions of GregTech. And the current GregTech community for suggestions and ideas."
authors="Muramasa, Rongmario, Abbe, Trinsdar"
description='''The Approved Continuation. Rewrite. And Re-envisioning of GregTech 5'''
[[dependencies.gti]]
    modId="antimatter"
    mandatory=true
    versionRange="[0.2,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.gti]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.gti]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"