import org.gradle.api.tasks.compile.JavaCompile
import org.gradle.jvm.toolchain.JavaLanguageVersion
plugins {
    id "maven-publish"
    id "idea"
    id "io.freefair.lombok" version "8.10.2" apply false
    id "net.neoforged.moddev.legacyforge" version "${mdg_version}" apply false
}
apply plugin: "net.neoforged.moddev.legacyforge"

//Print out JVM information so that we know what version is running. Extreamly useful for people to know when helping you.
println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

archivesBaseName = "${project.archive_base_name}"

def isCI = System.getenv("GITHUB_ACTION")
def gitHash() {
    String hash = System.getenv("GITHUB_SHA")
    if (hash != null) return hash.substring(0,8)
    return ""
}

allprojects {
    apply plugin: "maven-publish"
    apply plugin: "java"
    apply plugin: "idea"
    apply plugin: "io.freefair.lombok"
    group = project.maven_group
    version = "${project.mod_version}-${project.minecraft_version}"
    java.toolchain.languageVersion = JavaLanguageVersion.of(17)


    apply from: 'https://raw.githubusercontent.com/GT-Reimagined/GradleScripts/main/repositories.gradle'

    java {
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
    }

    if (isCI) {
        def isRELEASE = System.getenv("GITHUB_RELEASE")
        if (!isRELEASE){
            version = version + "-" + gitHash()
        }
        println("In CI mode")
    }
}

legacyForge {
    version = "${project.minecraft_version}-${project.forge_version}"
    parchment {
        minecraftVersion = project.minecraft_version
        mappingsVersion = project.mappings_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

mixin {
    add sourceSets.main, "gt5r.refmap.json"
    config "gt5r.mixins.json"
    config "gtlib.mixins.json"
    config "gtlib.rei.mixins.json"
}

repositories {
    maven {
        name = 'Su5eD'
        url = 'https://maven.su5ed.dev/releases/'
    }
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}
obfuscation {
    createRemappingConfiguration(configurations.localRuntime)
}

dependencies {
    //subprojects
    implementation(project(":tesseract-forge"))
    compileOnly(project(":tesseract-common"))
    implementation(project(":GT-Lib"))

    //gt lib deps
    implementation 'org.apache.commons:commons-collections4:4.4'
    //annotationProcessor 'org.spongepowered:mixin:0.8.5-SNAPSHOT:processor'
    annotationProcessor 'net.fabricmc:sponge-mixin:0.11.4+mixin.0.8.5'
    implementation("org.sinytra.mixinbooster:mixin-booster:${mixinbooster_version}+${minecraft_version}")
    implementation("org.jetbrains:annotations:26.0.1")
    modCompileOnly("mezz.jei:jei-${project.minecraft_version}-forge:${project.jei_version}")
    modCompileOnly("me.shedaniel:RoughlyEnoughItems-forge:${project.rei_version}")
    modCompileOnly("dev.emi:emi-forge:${project.emi_version}+${project.minecraft_version}")
    modCompileOnly("me.shedaniel.cloth:cloth-config-forge:${project.cloth_config_version}")
    modImplementation("com.blamejared.crafttweaker:CraftTweaker-forge-${project.minecraft_version}:${project.crafttweaker_version}")
    modImplementation("dev.trinsdar:arrp-forge:${project.arrp_version}")
    modImplementation("dev.trinsdar:terraform-utils-v1:${project.terraform_version}")
    modImplementation("org.gt-reimagined:structurelib-forge:${project.structurelib_version}-${project.minecraft_version}")
    modImplementation("com.teamresourceful.resourcefullib:resourcefullib-forge-${project.minecraft_version}:${project.resourcefullib_version}")
    modImplementation("maven.modrinth:carbon-config:${project.carbon_config_version}")
    modImplementation("dev.latvian.mods:kubejs-forge:${project.kubejs_version}")
    modImplementation("dev.latvian.mods:rhino-forge:${project.rhino_version}")
    modImplementation("dev.architectury:architectury-forge:${project.architectury_version}")
    modImplementation("brachy.modularui:modularui-mc${project.minecraft_version}:${project.mui_version}")

    //required gt5r deps
    modImplementation("org.gt-reimagined:gtcore:${rootProject.gt_core_version}-${rootProject.minecraft_version}")
    jarJar("org.gt-reimagined:gtcore:${rootProject.gt_core_version}-${rootProject.minecraft_version}")
    modRuntimeOnly("dev.trinsdar:terraform-wood-api-v1:${project.terraform_version}")
    jarJar("dev.trinsdar:terraform-wood-api-v1:${project.terraform_version}")
    modCompileOnly("org.appliedenergistics:guideme:${project.guideme_version}:api")
    modRuntimeOnly("org.appliedenergistics:guideme:${project.guideme_version}")
    //optional deps
    modImplementation("cc.tweaked:cc-tweaked-${project.minecraft_version}-forge:${project.cc_tweaked_version}")
    modImplementation("curse.maven:immersive-engineering-231951:${project.ie_version}")
    modImplementation("curse.maven:botania-225643:${botania_version}")
    modImplementation "maven.modrinth:forestry-community-edition:${forestry_version}"
    modImplementation("curse.maven:railcraft-reborn-901491:${railcraft_version}")
    //runtime deps
    modRuntimeOnly("curse.maven:worldstripper-250603:${project.worldstripper_version}")
    modRuntimeOnly("curse.maven:ae2-223794:${project.ae2_version}")
    //modImplementation("curse.maven:ctm-267602:3933537")
    modCompileOnly("curse.maven:terrafirmacraft-302973:${project.tfc_version}")
    //modRuntimeOnly("curse.maven:terrafirmacraft-302973:${project.tfc_version}")
    modRuntimeOnly("curse.maven:patchouli-306770:${project.patchouli_version}")
    modRuntimeOnly("curse.maven:the-twilight-forest-227639:${project.twilight_version}")
    //modRuntimeOnly("curse.maven:resourceful-config-714059:6231176")
    //modRuntimeOnly("curse.maven:botarium-704113:5486070")
    //modRuntimeOnly("curse.maven:ad-astra-635042:6262032")
    modRuntimeOnly("curse.maven:farmers-delight-398521:${project.farmers_delight_version}")
    modRuntimeOnly("curse.maven:sophisticated-backpacks-422301:${project.sophisticated_backpack_version}")
    modRuntimeOnly("curse.maven:sophisticated-core-618298:${project.sophisticated_core_version}")
    modRuntimeOnly("curse.maven:mouse-tweaks-60089:5338457")
    switch (project.runtime_itemviewer) {
        case "emi":
            modLocalRuntime("dev.emi:emi-forge:${emi_version}+${project.minecraft_version}")
            break
        case "rei":
            modLocalRuntime("me.shedaniel:RoughlyEnoughItems-forge:${project.rei_version}")
            modLocalRuntime("me.shedaniel.cloth:cloth-config-forge:${project.cloth_config_version}")
            break
        case "jei":
            modLocalRuntime("mezz.jei:jei-${project.minecraft_version}-forge:${project.jei_version}")
            break
    }

    switch (project.runtime_tooltip_mod) {
    //case "wthit":
    //    localRuntime "mcp.mobius.waila:wthit:neo-${project.wthit_version}"
    //    break
        case "jade":
            modLocalRuntime("curse.maven:jade-324717:${project.jade_version}")
            break
        case "top":
            modLocalRuntime("curse.maven:the-one-probe-245211:${project.top_forge_version}")
            break
    }
    //modRuntimeOnly("curse.maven:jamd-422981:${project.jamd_version}")
    modRuntimeOnly("mekanism:Mekanism:${project.minecraft_version}-${project.mekanism_version}")// Mekanism
    modRuntimeOnly("mekanism:Mekanism:${project.minecraft_version}-${project.mekanism_version}:additions")// Mekanism: Additions
    modRuntimeOnly("mekanism:Mekanism:${project.minecraft_version}-${project.mekanism_version}:generators")// Mekanism: Generators
    modRuntimeOnly("mekanism:Mekanism:${project.minecraft_version}-${project.mekanism_version}:tools")// Mekanism: Tools
}

jar{
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : "GT-Reimagined",
                'Specification-Version'   : '1', // We are version 1 of ourselves
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.version,
                'Implementation-Vendor'   : "GT-Reimagined",
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "MixinConfigs" : "gt5r.mixins.json"
        ])
    }
}

processResources {
    exclude('gtuassets1.14')
    exclude('assets/gt4r/textures/old_textures')
    var replaceProperties = [
            minecraft_version_range  : project.minecraft_version_range,
            forge_version_range      : project.forge_version_range,
            loader_version_range     : project.loader_version_range,
            gtlib_version_range      : project.gtlib_version_range,
            guideme_version_range    : project.guideme_version_range,
            version                  : project.mod_version,
            forestry_version_range   : project.forestry_version_range
    ]
    inputs.properties replaceProperties

    filesMatching("META-INF/mods.toml") {
        expand replaceProperties
    }
}
