# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
org.gradle.parallel=true

mod_version=0.4.0-alpha.1
archive_base_name=gt5r
mod_id=gt5r

mdg_version=2.0.82

mappings_version=2022.11.27
minecraft_version=1.19.2
forge_version=43.3.0

gt_core_version=0.3.0
terraform_version=4.2.4
arrp_version=0.6.8.1
jei_version=11.6.0.1018
emi_version=1.1.22
crafttweaker_version=10.1.50
kubejs_version=1902.6.2-build.74
rhino_version=1902.2.3-build.284
architectury_version=6.6.92
nightconfig_version=3.6.5
rei_version=9.2.784
cloth_config_version=8.3.134
resourcefullib_version=1.1.24
structurelib_version=3.0.0
carbon_config_version=kOTXPMWY
kotlin_version=1.8.21

maven_group=org.gt-reimagined

tesseract_archive_base_name=TesseractAPI
top_forge_version=3965693
worldstripper_version=3670854
ae2_version=4498141
patchouli_version=3846086
twilight_version=4337390
farmers_delight_version=4679315
sophisticated_backpack_version=4882591
sophisticated_core_version=4913626
jade_version=4914105
jamd_version=3807283