# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
org.gradle.parallel=true

mod_version=0.5.3-alpha.16
archive_base_name=gt5r
maven_group=org.gt-reimagined
mod_id=gt5r

#mc, mdg, forge/neoforge version
mdg_version=2.0.82
mappings_version=2023.09.03
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.20.2)
forge_version=47.4.0
forge_version_range=[47.1.3,)
loader_version_range=[47,)

#required dependencies
mixinbooster_version=0.1.1
gt_core_version=0.4.10.2
gtlib_version_range=[0.5.1,)
terraform_version=7.0.4
arrp_version=0.8.1.2
structurelib_version=4.0.0
carbon_config_version=hwMIqUzI
mui_version=3.3.0-SNAPSHOT
guideme_version=20.1.14
guideme_version_range=[20.1.14,)
cloth_config_version=1.1.136
resourcefullib_version=2.1.29
#not required
jei_version=15.20.0.116
emi_version=1.1.22
rei_version=12.1.785
crafttweaker_version=14.0.59
kubejs_version=2001.6.5-build.20
rhino_version=2001.2.3-build.10
architectury_version=9.2.14
nightconfig_version=3.6.5
jade_version=6855440
top_forge_version=6106996
kotlin_version=1.8.21

runtime_itemviewer=jei
runtime_tooltip_mod=jade

#mod compat
tesseract_archive_base_name=TesseractAPI
mekanism_version=10.4.16.80
forestry_version=2.10.0
forestry_version_range=[2.10.0,)
railcraft_version=8044082
cc_tweaked_version=1.117.1
worldstripper_version=4578579
ae2_version=7148487
patchouli_version=6164575
twilight_version=5468648
farmers_delight_version=6917255
sophisticated_backpack_version=7455143
sophisticated_core_version=7455151
jamd_version=4863428
tfc_version=7442504
ie_version=6206989
botania_version=7649894