# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
org.gradle.parallel=true

mod_version=0.3.1-alpha.13
archive_base_name=gt5r
mod_id=gt5r

mdg_version=2.0.82

mappings_version=2022.03.13
minecraft_version=1.18.2
forge_version=40.2.4

gt_core_version=0.2.19
terraform_version=3.1.5
arrp_version=0.6.7.1
jei_version=10.2.1.1004
crafttweaker_version=9.1.207
kubejs_version=1802.5.6-build.2
rhino_version=1802.2.1-build.255
architectury_version=4.12.94
nightconfig_version=3.6.5
resourcefullib_version=0.0.5
rei_version=8.3.557
structurelib_version=2.0.0
carbon_config_version=u2cqt0OR
kotlin_version=1.8.21

maven_group=org.gt-reimagined

tesseract_archive_base_name=TesseractAPI
top_forge_version=3671753
worldstripper_version=3670854
ae2_version=4498141
patchouli_version=3846086
twilight_version=4337390
farmers_delight_version=4679315
sophisticated_backpack_version=4882591
sophisticated_core_version=4913626
jade_version=5079263
jamd_version=3807283