modLoader="javafml"
license="LGPLv3"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/GT-Reimagined/GT5-Reimagined/issues"

[[mods]]
modId="gt5r"
version="${version}"
displayName="GT5 Reimagined"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/GT-Reimagined/GT5-Reimagined"
#logoFile="gregtech.png"
credits="GregoriusTechneticies for his previous versions of GregTech, the current GregTech community for suggestions and ideas, and Muramasa for the original GTI this is based off."
authors="Trinsdar"
description='''A Reimagining of GregTech 5U for modern minecraft versions'''
[[dependencies.gt5r]]
    modId="gtlib"
    mandatory=true
    versionRange="${gtlib_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.gt5r]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.gt5r]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.gt5r]]
    modId="mixinbooster"
    mandatory=true
    versionRange="[0.1.0+1.20.1,)"
    ordering="BEFORE"
    side="BOTH"