modLoader="javafml"
#loaderVersion="[${loader_version},)"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="gti"
#version="${version}"
version="0.0.1"
displayName="GregTech Intergalactical"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="GregoriusTechneticies for his work on GregTech"
authors="Muramasa"
description='''The approved continuation of GregTech 5 Unoficial'''
[[dependencies.gti]]
    modId="antimatter"
    mandatory=true
    #versionRange="[${antimatter_version},)"
    versionRange="0.0.1"
    ordering="AFTER"
    side="BOTH"
[[dependencies.gti]]
    modId="forge"
    mandatory=true
    #versionRange="[${forge_version},)"
    versionRange="31.0.1"
    ordering="NONE"
    side="BOTH"
[[dependencies.gti]]
    modId="minecraft"
    mandatory=true
    #versionRange="[${minecraft_version}]"
    versionRange="1.15.2"
    ordering="NONE"
    side="BOTH"